"""create recipes and batches tables

Revision ID: 653336fca96a
Revises:
Create Date: 2026-07-15 15:33:22.641157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653336fca96a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('batch_size_liters', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_og', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('target_fg', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('target_ibu', sa.Integer(), nullable=True),
    sa.Column('target_abv', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('brew_date', sa.Date(), nullable=False),
    sa.Column('brewer', sa.String(length=50), nullable=False),
    sa.Column('water_volume_liters', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches')
    op.drop_table('recipes')
    # ### end Alembic commands ###
